### PR TITLE
Update project license from LGPL to MIT

### LINKED ISSUE #33: MIT License?
**Is your feature request related to a problem? Please describe.**
Would love to see the license change.

**Describe the solution you'd like**
LGPL -> MIT

**Describe alternatives you've considered**
BSD, Apache, ...

**Additional context**
Would love to see it happen!

### PR DESCRIPTION
**Pull request by marcofavorito**
## Proposed changes

This PR changes:
- the LICENSE file from LGPL v3.0 to MIT
- the copyright license header in all files, following Google Open Source directives: https://opensource.google/documentation/reference/releasing/licenses
- the scripts/check_copyright.py, in accordance with the above
- update other Python package metadata and the README

## Fixes

Fix #33

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [ ] I have read the [CONTRIBUTING](../blob/master/CONTRIBUTING.md) doc
- [ ] I am making a pull request against the `develop` branch (left side). Also you should start your branch off our `develop`.
- [X] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works

## Further comments

n/a

### CODE REVIEW

**Comment by haz** [comment]
- https://stackoverflow.com/questions/71673404/importerror-cannot-import-name-unicodefun-from-click
- https://github.com/AI-Planning/pddl/blob/master/tox.ini
- https://github.com/AI-Planning/pddl/blob/master/Pipfile.lock
- https://github.com/AI-Planning/pddl/blob/master/Pipfile

**Comment by marcofavorito** [comment]
#42 should be merged before this PR; in this way, GitHub Actions check will pass also for this PR.

**Comment by marcofavorito** [comment]
I rebased this branch over current `develop`.

**Comment by haz** [comment]
So is this ready to merge? Checks seem to be passing now...

**Comment by francescofuggitti** [comment]
Wait, some acks are missing in the README. I'm going to add them now.

**Pull request merged**
