### PR TITLE
Return type annotation for Problem and Domain transformers. Fixed requirements type annotation in DomainTransformer.

### PR DESCRIPTION
**Pull request by MichaelJFishman**
## Proposed changes

A few type annotations. I didn't add any annotations to `parse_problem` and `parse_domain`, because I didn't want to `Domain` and `Problem` imports to the `__init__.py`.

## Fixes

Adds return type annotation for Problem and Domain transformers, by specifying that type parameter when subclassing `Transformer`. Also annotated that `Domain.__call__` and `Problem.__call__` return `Domain` and `Problem`, respectively.

Fixed `_requirements` type annotation in `DomainTransformer`.
## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [x] I have read the [CONTRIBUTING](../blob/main/CONTRIBUTING.md) doc
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works

I ran the tests and got the following output. I can't tell from this where mypy/evaluation failed. 

```
========================================================= 2117 passed in 347.71s (0:05:47) =========================================================
.pkg: _exit> python /home/johnny/mambaforge/envs/scoping_new_z3/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
  check-copyright: OK (0.18=setup[0.14]+cmd[0.05] seconds)
  black-check: OK (3.71=setup[2.67]+cmd[1.03] seconds)
  isort-check: OK (1.97=setup[1.73]+cmd[0.24] seconds)
  docs: OK (10.27=setup[9.62]+cmd[0.65] seconds)
  flake8: OK (4.05=setup[3.20]+cmd[0.86] seconds)
  mypy: FAIL code 1 (7.70=setup[5.04]+cmd[2.65] seconds)
  py37: SKIP (0.12 seconds)
  py38: SKIP (0.01 seconds)
  py39: SKIP (0.01 seconds)
  py310: OK (362.15=setup[13.69]+cmd[348.46] seconds)
  evaluation failed :( (390.27 seconds)
```

### CODE REVIEW

**Comment by haz** [comment]
Thanks for the fixes here! You can find more details on the blocking error here: https://github.com/AI-Planning/pddl/actions/runs/7240077134/job/19740335600?pr=102

**Comment by marcofavorito** [comment]
Hi @MichaelJFishman, I would like to push some commits to this PR. Could you please "Allow edits from maintainers"? [(see this link)](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)

**Comment by MichaelJFishman** [comment]
Thanks for the commits!

It looks like "Allow edits from maintainers" is already enabled on this PR. Are you still unable to edit it?

image

**Comment by marcofavorito** [comment]
> Thanks for the commits!
> 
> It looks like "Allow edits from maintainers" is already enabled on this PR. Are you still unable to edit it?
> 
> image
> 
> Edit: @marcofavorito

Confirmed, thanks :)

**Review by marcofavorito — APPROVED** [review]
LGTM, thanks @MichaelJFishman !

**Pull request merged**
