### PR TITLE
Forall fix

### PR DESCRIPTION
**Pull request by aefrank**
## Proposed changes

- Fix bugs in parsing and printing `forall` effects of actions.
- New test re-parses generated domain strings and checks for equivalence to ensure output PDDL is syntactically valid and free of mutations.

#### Supplemental changes
- Added new example PDDL domain from IPC 2014 that uses a `forall` effect to demonstrate bug and fix.
- **[behavior change]** Added comparing type equivalence to `__eq__` dunder method of `Variable` class to enable new test to catch dropped type annotations.
- Modified tox.ini to allow cli to specify individual tests or labels.
- [aesthetic] Removed trailing whitespace from parameter lists generated by `domain_to_string`.

Details below.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [x] I have read the [CONTRIBUTING](../blob/main/CONTRIBUTING.md) doc
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works

### Primary Bugfix: Incorrect parameter handling for `forall` effects.
`pddl` incorrectly handles the parameters of `(forall (?x - type) ...)` effects in both parsing into Python objects and in generating PDDL strings. The bugs come up in `forall` expressions that occur in the `:effect` field of PDDL actions and the `Forall` objects they are translated to. Note that other occurances of `forall` in PDDL that are interpreted as `ForallConditions` (e.g. those occurring in action preconditions) do not exhibit this bug.

#### [Context]
I noticed this bug when I tried to work with the [maintenance-sequential-satisficing](https://github.com/potassco/pddl-instances/tree/master/ipc-2014/domains/maintenance-sequential-satisficing) domain file from IPC 2014. I'm going to use the effect `(forall (?p - plane) (when (at ?p ?day ?airport) (done ?p)))`[^1] from this domain as a running example. I tried to parse, write to string, and re-parse `domain.pddl` without any modifications, i.e. `domain_parser(domain_to_string(domain_parser('domain.pddl')))`. I was met with the following error:
```
lark.exceptions.UnexpectedToken: Unexpected token Token('NAME', 'p') at line 8, column 50.
               Expected one of: 
                       * RPAR
                       * QMARK
               Previous tokens: [Token('LPAR', '(')]
```

[^1]: The original file actually uses `(forall (?plane - plane) ...)`, but I modified it here to distinguish between the variable name `p` and the type `plane`. 

#### [Bug]
Turns out the parameters of `forall` effects in the PDDL string generated by `domain_to_string` were printed without `?` prefix or type annotations: `(forall (p) (when (at ?p ?day ?airport) (done ?p)))`. For this particular error, the missing `QMARK` token was the source of the UnexpectedToken exception.[^2]
[^2]: As an aside, the parser exception stating that it would have accepted `RPAR` as well seems to imply that `(forall () ...)` with no variables to quantify over is a valid PDDL string. Is this intentional?

#### [Fixes]
Addressing this required two main fixes:
1. Translating parameter tokens to`Variable` objects before passing to `Forall` effect constructor so the parameters are printed with the variable `?` prefix.
2. Modifying `Forall.__str__()` method to print type annotations using the `_typed_parameters` method from `pddl/helpers.base.py`.

For each fix, I looked through the codebase for working instances of typed parameter lists `(?var1 - type1 ?var2 - type2 ...)` generated from collections of `Variable` objects that I could repurpose for `Forall` effects. I used two primary references: parameters of `forall` predicates found outside the `:effect` field of PDDL actions (`ForallCondition.variables`); and the `:parameters` field of PDDL actions (`Action.parameters`).

1. **Translating parameter tokens to`Variable` objects before passing to `Forall` effect constructor so the parameters are printed with the variable `?` prefix.**

	*Bug --* When the parser comes across a `forall` effect, the tokens are passed to the`c_effect` method of `pddl/parser/domain.py::DomainTransformer` to construct a `Forall` object. The parameter tokens are encoded as a mapping (e.g. `{Token('NAME', 'p'):{'plane'}}`), which are passed to the constructor through the `variables` kwarg. The constructor runs `ensure_set` on this, which drops the `{'plane'}` type annotation, resulting in`variables=frozenset({Token('NAME', 'p')})`. Then, when `Forall.__str__()` runs `map(str, self.variables)`, `str(frozenset({Token('NAME', 'p')}))` returns `p` with no additional formatting.

	*Reference --* In contrast, the methods `gd_quantifiers` (for non-effect `forall` conditions) and `action_parameters` construct `Variable` objects from the raw parameter tokens via `[Variable(name, tags) for name, tags in <param_tokens>.items()]`.  

	**Fix --** Adding this preprocessing step to the `c_effect` method means the `variables` field of the constructed `Forall` object now contains a collection of `Variables`[^3] whose `__str__` dunder methods automatically inserts the  `?` prefix when generating the PDDL string, e.g.  `(forall (?p) (when (at ?p ?day ?airport) (done ?p)))`.  

	However, type annotations were still missing. For a typed PDDL domain, this is incorrect, as the type is needed to specify the domain over which the variable is quantified. The type information was definitely now available in the `type_tags` field of each `Variable` object in `Forall._variables`, but the annotations were still not being included in the generated PDDL strings.

[^3]: As a bonus, this fix ensures that the field is in agreement with the type hints defined in `pddl/logic/effects.py`.

2. **Modifying `Forall.__str__()` method to print type annotations using `_typed_parameters` function.**

	*Bug --* During a call to `domain_to_string`, a `forall` effect is generated by calling `Forall.__str__`. This returns `f"({Symbols.FORALL.value} ({' '.join(map(str, self.variables))}) {self.effect})"`, which uses `Variable.__str__` to determine how to represent each parameter. However, `Variable.__str__` returns `f"?{self._name}"`, which prints only the variable name with no type annotation. This could be considered either a bug in `Variable.__str__` or `Forall.__str__`. Though there could be an argument for `Variable.__str__` to always include type annotations when present, I chose to modify the latter to avoid impacting other parts of the library that currently use `Variable.__str__` without complaint. 

	*Reference --* Interestingly, unlike for fix (1), the typed parameter strings generated in `ForallCondition.__str__` and `Action.__str__` use different code. `ForallCondition.__str__` (inherited from `QuantifiedCondition`) constructs its parameter list via a list comprehension `" ".join([f"{v}{build_tags(v.type_tags)}"  for v in  self.variables])` using a local function `build_tags(tags)` that generates the type annotation for a single variable. On the other hand, `Action.__str__`, generates its parameter list via `({_typed_parameters(self.parameters)})"`, where `_typed_parameters` imported from `pddl/helpers/base.py` processes the entire parameter list internally.

	**Fix:** Because `_typed_parameters` seemed to be defined specifically to generate this kind of PDDL string, I chose to follow the example of the `Action` class[^4], changing the parameter lists portion of `Forall.__str__` from `({' '.join(map(str, self.variables))})"` to `({_typed_parameters(self.variables)}`. With this change, the generated string properly includes type annotations, e.g. `(forall (?p - plane) (when (at ?p ?day ?airport) (done ?p)))`. 

[^4]: For consistency and universality, it might be nice to change `QuantifiedCondition` to use the same `_typed_parameters`-based code. That way if it's ever needed to change how typed parameter lists are printed, only one function needs to be modified.

---

### New test

It seems like this bug went under the radar because it didn't cause Python errors in a single round of parsing and printing. I added a new test to demonstrate the bug prior to this PR and validate the proposed fix. The test is located in `tests/test_formatter.py`. The test performs four main steps for the domain files specified in `conftest.py::DOMAIN_FILES`: 
1. Parse the PDDL domain file into a Python `Domain` object via `domain_parser`,
2. Generate a new PDDL string of the domain via `domain_to_string`, 
3. Parse the new PDDL string into a new `Domain` object via `domain_parser`, and
4. Assert that the first and second `Domain` objects are equivalent as defined by `Domain.__eq__`.

By re-parsing the output of `domain_to_string`, the test ensures that the generated PDDL domain files are syntactically valid (e.g. that no `?` variable prefixes are dropped). Furthermore, by asserting that parsing the "re-translated" PDDL file is equivalent to parsing the original file, ensuring that no mutations change the domain's semantic content. This test should be valuable in verifying that translation between PDDL and Python is working as expected far beyond this bug.

#### Modified `pddl/logic/terms.py::Variable::__eq__`

To enable `assert actual_domain_obj == expected_domain_obj` to catch dropped type tags, I modified `Variable.__eq__` to include the check `self.type_tags == other.type_tags`. Notably, if the variables are untyped, `None==None` evaluates to `True`, so this addition does not interfere with untyped equivalence. I feel including a type comparison when evaluating equivalence of variables is reasonable, as variables with different types will be treated differently throughout the PDDL logic. 

I admit I'm not convinced that a simple `==` check is the best encoding of this concept, particularly if one of the variables has type information and the other is only a variable name. It may preferred in the future to change this into a more advanced subtyping check. Alternatively, perhaps this sort of type tag equivalence should be defined in the parent `Term` class so that all subclasses inherit it by default. I made sure to include this change in its own commit to make it easy to remove if desired.

---

### Changes to `tox.ini`

As I was running the test suite on the PR, I found myself wanting to run specific tests that had failed individually to debug, or wanting to skip the code tests after I knew they ran fine to focus on linting. These changes allow individual tests to be passed to the cli positionally with `tox ... -- path/to/test_file.py::TestClassName::test_method`, or to choose to run only code tests vs. linting testenvs with labels `tox -m code` or `tox -m meta`. When these aren't passed, tox behaves as before, with `{posargs}` defaulting to the `pddl tests`. I made sure to include this change in its own commit to make it easy to remove if desired.

---

### Remove trailing whitespace in parameter lists from`pddl/helpers/base::_typed_parameters`

For whatever reason, `_typed_parameters` included an extra space before the closing right paren (e.g. `(?var1 - type1 ?var2 - type2 )`) where in all other cases trailing whitespace is trimmed. For consistency (and my own aesthetic preference), I added `.strip()` to the output of `_typed_parameters` to remove the trailing space. 

This made `tests/test_docs/test_readme.py` fail because it checked that the domain string generated by the example input would be EXACTLY equivalent to the example output, which included the trailing whitespace. To let this test pass, I had to remove the trailing whitespace from the action parameters in the README.md. I made sure to include these changes in their own commit to make it easy to remove if desired.

### CODE REVIEW

**Review by haz — CHANGES_REQUESTED** [review]
This is amazing stuff. Thank you so much for your efforts, @aefrank !

I've been meaning to run the same parse > dump > parse > compare loop across all problems in the planning.domains API, but just haven't found the time yet. Obviously some rough edges still that the technique can catch, and you've highlighted a major one.

While I'm inclined to like your style better, our auto-code checker does not. Just a few small suggestions, and I'll dig deeper into your footnotes for potential followup issues/discussion.

Thank you again!

**Comment by aefrank** [comment]
Glad its looking good so far! I committed the code style changes - for whatever reason they weren't flagged locally. 

Yeah, I figured the re-parsing loop was a good general test to add to the suite. Everything without forall effects seemed to pass it, which seems like a good sign that not too many bugs slipped in under the radar! 

I intend to do the same sort of process with PDDL problem files to make sure `forall` effects are working and the files can be parsed and re-parsed. I'd intended to include it in this PR, but I started to run into some issues and decided it would be best to just check in with the domain PR first. Keep things simple before I add in more chaos, haha.

**Comment by haz** [comment]
> As an aside, the parser exception stating that it would have accepted RPAR as well seems to imply that (forall () ...) with no variables to quantify over is a valid PDDL string. Is this intentional?

Just double checked the BNF. It is indeed the case (overloads it so that the same part can be used for empty parameters on an action). So I think we're ok here.

> For consistency and universality, it might be nice to change QuantifiedCondition to use the same _typed_parameters-based code. That way if it's ever needed to change how typed parameter lists are printed, only one function needs to be modified.

I'd have to agree with this! Any chance you'd be up for opening an issue that highlights the two core ways it's done? No need to jump on it (unless you can't get enough of `pddl` wrangling ;)), but it would be good to have it in the backlog.

> I intend to do the same sort of process with PDDL problem files to make sure forall effects are working and the files can be parsed and re-parsed. I'd intended to include it in this PR, but I started to run into some issues and decided it would be best to just check in with the domain PR first. Keep things simple before I add in more chaos, haha.

As much as I like to embrace the chaos, good call. Thanks again!

**Review by haz — APPROVED** [review]

**Comment by aefrank** [comment]
> > For consistency and universality, it might be nice to change QuantifiedCondition to use the same _typed_parameters-based code. That way if it's ever needed to change how typed parameter lists are printed, only one function needs to be modified.

> I'd have to agree with this! Any chance you'd be up for opening an issue that highlights the two core ways it's done? No need to jump on it (unless you can't get enough of pddl wrangling ;)), but it would be good to have it in the backlog.

Done! #72

**Pull request merged**
