### PR TITLE
Override equal for derived predicates

### PR DESCRIPTION
**Pull request by francescofuggitti**
## Proposed changes

Add custon __eq__ operator to Predicates and Derived Predicates

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [x] I have read the [CONTRIBUTING](../blob/main/CONTRIBUTING.md) doc
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by haz — CHANGES_REQUESTED** [review]
Any chance we could get a test on this one? I assume it was breaking on `==` checks before the change?

**Review by haz — CHANGES_REQUESTED** [review]
Any chance we could get a test on this one? I assume it was breaking on `==` checks before the change?

**Comment by haz** [comment]
`codecov` is not happy ;)

image

**Review by marcofavorito — APPROVED** [review]
LGTM

**Review by haz — APPROVED** [review]
Thanks for the test cases!

**Pull request merged**
