### PR TITLE
Taking the latest of all.

### PR DESCRIPTION
**Pull request by haz**
## Proposed changes

Testing out what would happen if we just take the latest of every package in the dev requirements.

### CODE REVIEW

**Comment by haz** [comment]
Thoughts on nuking the specific versions? We have a long list of auto-generated PR's, and this PR seems to bring us back up to snuff.

I had to ignore a single vulnerability listed in Jinja2: https://data.safetycli.com/v/70612/97c/

It's a bit odd, as it's listed for every version of the package (`>=0`). Also created half a decade ago and updated only 3 days ago.

> Created at Feb 15, 2019 Updated at Aug 06, 2024

So I'm assuming it's just a bug with the bug database?

If we don't want `*` versions on the packages (it's all the dev packages -- not lark+click), then we'll need to find a way to update them to reasonable ranges.

**Review by francescofuggitti — APPROVED** [review]
LGTM, thanks!

**Comment by haz** [comment]
Not even any discussion? ;)

Feels like a pretty drastic move to just accept the latest version, but as long as we keep checking in, it should be alright.

**Comment by marcofavorito** [comment]
> Not even any discussion? ;)
> 
> Feels like a pretty drastic move to just accept the latest version, but as long as we keep checking in, it should be alright.

LGTM too. 

In the end, `Pipfile` does not affect the package's dependencies, as the only dependencies are `lark` and `click` in `setup.py`, and their version requirements are opportunely upper-bounded. 

However, there might be issues with the software's behavior in the local **development** environment and the environments of GitHub Actions CI. It often happened to me in other projects that CI jobs broke in weird and subtle ways due to a recent release of a random (sub-)dependency in the dependency tree of the local dev env, which nevertheless was compatible with the version requirements in the `Pipfile`. 

On the upside, this incentivizes a more frequent refresh of the local dev environment in case of inconsistencies between local environments among developers/contributors and CI environments.

Questions:
- I see that in `tox.ini`, the version requirements for the development dependencies are unchanged. This means that, when using the Python interpreter managed by `pipenv`, the local execution of dev jobs (lint/static checks, tests etc.) might give different results one on CI or when using `tox` because the latter might point to older versions of the dev dependencies. 
- The (sub-)dependencies locked via `pipenv` might be incompatible with the (sub-)dependencies of the `pddl` package because `lark` and `click` are not included in the `Pipfile`. Perhaps we could just add `lark` and `click` in the Pipfile with the same version requirements as in `setup.py`.

**Comment by haz** [comment]
Both excellent questions/points! I've got a few min before my next meeting, so will take a crack. How would you advise I test the tox.ini changes locally? (don't think the CI/CD would run through it, but could be wrong...)

**Comment by haz** [comment]
Chasing down issues with lazy fixtures...almost there...

**Comment by haz** [comment]
Ok, mistune had a major revision change, and had to make modifications like [this](https://github.com/AI-Planning/pddl/pull/120/files#diff-69da64b8c3d8e4b3b610386736b8604962293d51021d4ce5e48983a10a8fd093R59) and [this](https://github.com/AI-Planning/pddl/pull/120/files#diff-69da64b8c3d8e4b3b610386736b8604962293d51021d4ce5e48983a10a8fd093R82).

Also, pytest-lazy-fixture went defunct, and was picked up by another initiative:
- https://www.mail-archive.com/commits@tvm.apache.org/msg105447.html
- https://github.com/TvoroG/pytest-lazy-fixture/issues/65
- https://github.com/dev-petrov/pytest-lazy-fixtures
- https://github.com/AI-Planning/pddl/pull/120/files#diff-e52e4ddd58b7ef887ab03c04116e676f6280b824ab7469d5d3080e5cba4f2128R20

Can confirm that a fresh `tox` works locally. Should now be set to approve+merge!

**Update:** Just read @francescofuggitti's response. A more unified might work, ya. For now, I'm ok with dependency hunting to keep us up-to-date with the testing side. The important part is deployment, and we're locked into only two dependencies there. If we ever want to scale back and lock in versions, we can just look to the Pipfile.lock for what's currently working :P

**Pull request merged**
