### PR TITLE
🚧 [WIP] 🔢 Add support for numerical fluents

### PR DESCRIPTION
**Pull request by MathisFederico**
## Proposed changes

Add support for numerical fluents introduced in [PDDL 2.1](https://planning.wiki/ref/pddl21).

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [x] I have read the [CONTRIBUTING](../blob/main/CONTRIBUTING.md) doc
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works

## Further comments

I'm doing the Pull Request early so we can iterate quickly if I need to change something.

### CODE REVIEW

**Comment by haz** [comment]
@MathisFederico Heya! This PR stalled? Anything I can help with to push it along?

**Comment by MathisFederico** [comment]
> @MathisFederico Heya! This PR stalled? Anything I can help with to push it along?

Hey !
I ended up using unified_planning because it fits my needs !
Sorry for this PR

**Comment by haz** [comment]
Well that's quite unfortunate -- looks like you made a great start, and the broader planning community could really use the support.

Want to characterize where you left things off, and perhaps I can pick it up from here?

**Comment by MathisFederico** [comment]
You can pickup from here if you want sure !

**Pull request closed without merging**
